CREATE TABLE `Film` (
    `FilmID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Title` VARCHAR(255) NULL,
    `Genre` VARCHAR(255) NOT NULL,
    `Director` VARCHAR(255) NOT NULL,
    `Release_Date` YEAR NOT NULL,
    `Description` LONGTEXT NOT NULL,
    `Poster` BLOB NOT NULL,
    `Rating` DECIMAL(8, 2) NOT NULL
    
);
CREATE TABLE `Roles` (
    `RolesID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `AdminID` BIGINT NOT NULL,
    `Roles` TINYINT(1) NOT NULL
);

CREATE TABLE `User` (
    `UserID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Username` VARCHAR(255) NOT NULL,
    `Email` VARCHAR(255) NULL,
    `Password` VARCHAR(255) NOT NULL
);

CREATE TABLE `User_Rating` (
    `RatingID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `FilmID` BIGINT UNSIGNED NOT NULL,
    `UserID` BIGINT UNSIGNED NOT NULL,
    `Rating` DECIMAL(8, 2) NOT NULL,
    `RatingDescription` TEXT NOT NULL,
    `Genre` VARCHAR(255) NOT NULL,
    FOREIGN KEY (`FilmID`) REFERENCES `Film`(`FilmID`),
    FOREIGN KEY (`UserID`) REFERENCES `User`(`UserID`)
);

CREATE TABLE `Admin` (
    `AdminID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `FilmID` BIGINT UNSIGNED NOT NULL,
    `User` VARCHAR(255) NOT NULL,
    `Email` VARCHAR(255) NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    FOREIGN KEY (`FilmID`) REFERENCES `Film`(`FilmID`)
);

CREATE TABLE `Permissions` (
    `PermissionID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `UserID` BIGINT UNSIGNED NOT NULL,
    `UserPermissions` TINYINT(1) NOT NULL,
    FOREIGN KEY (`UserID`) REFERENCES `User`(`UserID`)
);
